server:
  port: 9090
spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: cn.idea360.oracle.model
#  type-handlers-package: com.example.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: mapper/*.xml

logging:
  level:
    root: info