-- 微信用户表
CREATE TABLE "JS_WECHAT_USER" (
"ID" NUMBER(18, 0) NOT NULL ,
"OPENID" VARCHAR2(128 BYTE) NOT NULL,
"NICKNAME" VARCHAR2(128 BYTE) NULL,
"SEX" NUMBER(1,0) DEFAULT 0,
"LANGUAGE" VARCHAR2(64 BYTE) NULL,
"CITY" VARCHAR2(64 BYTE) NULL,
"PROVINCE" VARCHAR2(64 BYTE) NULL,
"COUNTRY" VARCHAR2(64 BYTE) NULL,
"HEADIMGURL" VARCHAR2(256 BYTE) NULL,
"SUBSCRIBE_TIME" NUMBER DEFAULT 0,
"REMARK" VARCHAR2(128 BYTE) NULL,
"GROUPID" NUMBER DEFAULT 0,
"SUBSCRIBE_SCENE" VARCHAR2(64 BYTE) NULL,
"QR_SCENE" NUMBER DEFAULT 0,
"QR_SCENE_STR" VARCHAR2(64 BYTE) NULL,
"USER_ID" VARCHAR2(128 BYTE) NOT NULL,
PRIMARY KEY ("ID")
);
-- openid唯一
CREATE UNIQUE INDEX IDX_JS_WECHAT_USER_OPEN_ID on JS_WECHAT_USER(OPENID);
-- 主键序列
CREATE SEQUENCE JS_WECHAT_USER_ID_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE;

COMMENT ON table JS_WECHAT_USER IS '微信个人信息表';
COMMENT ON COLUMN "JS_WECHAT_USER"."OPENID" IS '用户的标识，对当前公众号唯一';
COMMENT ON COLUMN "JS_WECHAT_USER"."NICKNAME" IS '用户的昵称';
COMMENT ON COLUMN "JS_WECHAT_USER"."SEX" IS '用户的性别，值为1时是男性，值为2时是女性，值为0时是未知';
COMMENT ON COLUMN "JS_WECHAT_USER"."LANGUAGE" IS '用户的语言，简体中文为zh_CN';
COMMENT ON COLUMN "JS_WECHAT_USER"."CITY" IS '用户所在城市';
COMMENT ON COLUMN "JS_WECHAT_USER"."PROVINCE" IS '用户所在省份';
COMMENT ON COLUMN "JS_WECHAT_USER"."COUNTRY" IS '用户所在国家';
COMMENT ON COLUMN "JS_WECHAT_USER"."HEADIMGURL" IS '用户头像';
COMMENT ON COLUMN "JS_WECHAT_USER"."SUBSCRIBE_TIME" IS '用户关注时间，为时间戳';
COMMENT ON COLUMN "JS_WECHAT_USER"."REMARK" IS '公众号运营者对粉丝的备注';
COMMENT ON COLUMN "JS_WECHAT_USER"."GROUPID" IS '用户所在的分组ID';
COMMENT ON COLUMN "JS_WECHAT_USER"."SUBSCRIBE_SCENE" IS '返回用户关注的渠道来源';
COMMENT ON COLUMN "JS_WECHAT_USER"."QR_SCENE" IS '二维码扫码场景';
COMMENT ON COLUMN "JS_WECHAT_USER"."QR_SCENE_STR" IS '二维码扫码场景描述';
COMMENT ON COLUMN "JS_WECHAT_USER"."USER_ID" IS '易聊客服id';

